Feature/contrast color pie chart
deepaknevdepsl/observability pull request #4
Opened 2022-05-28 03:33 UTC by deepaknevdepsl

### Description
Pie chart contrast color for chart portion, if chart color selected as single.

### Issues Resolved
Change portion border color for single dark color.

### Check List
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-30 11:17 UTC, abasatwar requested changes

2022-05-30 11:17 UTC, abasatwar commented on dashboards-observability/.cypress/integration/1_event_analytics.spec.js
>  });
add empty line.

2022-05-30 11:17 UTC, abasatwar commented on dashboards-observability/.cypress/utils/event_constants.js
>  };
same as above.

2022-05-31 04:17 UTC, deepaknevdepsl commented on dashboards-observability/.cypress/integration/1_event_analytics.spec.js
>  });
Added empty line at the end of file.

2022-05-31 04:17 UTC, deepaknevdepsl commented on dashboards-observability/.cypress/utils/event_constants.js
>  };
Added empty line at the end of file.

2022-05-31 08:39 UTC, deepaknevdepsl commented
Creating single common PR for pie chart, hence closing this PR.

2022-05-31 08:39 UTC, closed without merging