Pie chart legends, chart color contrast and cypress test cases
deepaknevdepsl/observability pull request #5
Opened 2022-05-31 08:37 UTC by deepaknevdepsl

Signed-off-by: Deepak Nevde <deepak_nevde@persistent.com>

### Description
1] Added legends for Pie chart and added cypress test cases for same.
2] Converted chart selected color into contrast color to see the chart Pisces and added cypress test cases.

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-31 11:11 UTC, abasatwar approved these changes

2022-06-01 10:00 UTC, spattnaik requested changes

2022-06-01 10:00 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +    return (Number(`0x1${hex}`) ^ 0xFFFFFF).toString(16).substr(1).toUpperCase()
Shouldn't 0xFFFFFF be replaced with a constant?

2022-06-01 12:41 UTC, deepaknevdepsl commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +    return (Number(`0x1${hex}`) ^ 0xFFFFFF).toString(16).substr(1).toUpperCase()
Moved to constants.

2022-06-16 06:04 UTC, deepaknevdepsl commented
External PR merged, so closing this PR.

2022-06-16 06:04 UTC, closed without merging